project:
  type: website
  output-dir: docs
  resources: 
    - videos
    - CNAME

website:
  title: 植物的一生 🌱
  description: 配套教科书的官方学习资源库
  google-analytics: G-V0ZZB038TJ
  navbar:
    background: "#78c2ad"
    left:
      - text: 主页
        href: index.qmd
      - text: 课前预习资料
        href: pre-class.qmd
      - text: 其他资源
        href: resources.qmd
      - text: 老师教学资源
        href: teacher-resources.qmd
      - text: 关于我们
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/chenxizhou-520/plant-textbook
  page-footer:
    center: |
      ![网站总浏览量](https://visitor-badge.laobi.icu/badge?page_id=chenxizhou-520.plant-textbook)
  search: true

format:
  html:
    theme: minty
    toc: true
    toc-title: 本页目录
    lang: zh
    css: styles.css